<a href="https://colab.research.google.com/github/Sangeetha231005/MLops-training/blob/main/Save_and_Load_the_Model_using_Pickle_and_joblib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Machine Learning With Python : Save and Load the Trained Model**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Flood_detection/flood.csv')

In [ ]:
df.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475


In [ ]:
X = df[['MonsoonIntensity']]
y = df['FloodProbability']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_

array([0.00489028])

In [ ]:
model.intercept_

np.float64(0.475227441857988)

In [ ]:
prediction = model.predict(
    pd.DataFrame([[7]], columns=['MonsoonIntensity'])
)
print(prediction)

[0.50945942]


**Save Model To a File using Pickle :**

In [ ]:
import pickle

In [ ]:
with open('flood_model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [ ]:
with open('flood_model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([0.00489028])

In [ ]:
mp.intercept_

np.float64(0.475227441857988)

In [ ]:
mp.predict(
    pd.DataFrame([[7]], columns=['MonsoonIntensity'])
)
print(prediction)

[0.50945942]


**Save Model using Joblib :**

In [ ]:
import joblib

In [ ]:
joblib.dump(model, 'flood_model_joblib')

['flood_model_joblib']

In [ ]:
mj = joblib.load('flood_model_joblib')

In [ ]:
mj.coef_

array([0.00489028])

In [ ]:
mj.intercept_

np.float64(0.475227441857988)

In [ ]:
mj.predict(
    pd.DataFrame([[7]], columns=['MonsoonIntensity'])
)
print(prediction)

[0.50945942]
